import React from "react";
import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";
import { PageHero } from "@/components/ui/PageHero";
import { LandRadarVisualizer } from "@/components/interactive/LandRadarVisualizer";
import { generatePageMetadata } from "@/lib/metadata";
import {
  Compass,
  Database,
  Layers,
  ShieldCheck,
  CheckCircle2,
  AlertCircle,
  FileCheck2,
  ArrowRight,
  UserCheck,
  Search,
  Scale,
  Binary,
} from "lucide-react";

export const metadata = generatePageMetadata({
  title: "Land Radar — Spatial Intelligence Powering Human Acquisition",
  description:
    "Explore how Entire UK uses Land Radar, our proprietary deterministic spatial intelligence platform, to screen land parcels, evaluate title boundaries, and empower property director decisions.",
  path: "/land-radar",
});

export default function LandRadarPublicPage() {
  const dataStreams = [
    {
      title: "HM Land Registry (HMLR)",
      metric: "Cadastral Title Extents",
      desc: "Direct ingestion of registered title boundaries, freehold and leasehold tenure classifications, restrictive covenants, and legal charge records.",
      focus: "Resolving parcel-to-title discrepancies and identifying unencumbered ownerships.",
    },
    {
      title: "Ordnance Survey MasterMap",
      metric: "Highways & Physical Topology",
      desc: "Centimetre-accurate topographic and highways polygon datasets defining physical carriageways, adopted road boundaries, and natural physical edges.",
      focus: "Determining authentic highway frontage and eliminating landlocked parcel illusions.",
    },
    {
      title: "Environment Agency & Statutory Bodies",
      metric: "Environmental & Geological Constraints",
      desc: "Statutory geospatial datasets covering Flood Zones 2, 3a and 3b, Sites of Special Scientific Interest (SSSI), Ancient Woodland, and Groundwater Protection Zones.",
      focus: "Applying strict fatal blocker exclusions before capital or professional time is deployed.",
    },
    {
      title: "LPA Planning Repositories",
      metric: "Local Plan Allocations & 5YHLS",
      desc: "Live tracking of Local Planning Authority housing land supply deficits, strategic call-for-sites submissions, Green Belt reviews, and historical planning applications.",
      focus: "Targeting planning jurisdictions where housing need creates acute policy tailwinds.",
    },
  ];

  const ledgerLayers = [
    {
      layer: "Layer 1",
      name: "Authoritative Source Facts",
      icon: Database,
      desc: "Raw, unmodified records ingested directly from statutory authorities (HMLR title polygons, OS geometry, EA flood shapes). Each fact retains full cryptographic provenance.",
      principle: "Never mutated, never inferred.",
    },
    {
      layer: "Layer 2",
      name: "Deterministic Spatial Derivations",
      icon: Binary,
      desc: "Calculated spatial metrics produced by rigorous computational geometry in British National Grid (EPSG:27700): exact surface area in hectares, frontage meters to adopted road, distance to settlement.",
      principle: "Fully reproducible, zero probabilistic guesswork.",
    },
    {
      layer: "Layer 3",
      name: "Professional Human Judgements",
      icon: UserCheck,
      desc: "Formal qualitative evaluations recorded by Entire UK acquisition directors and specialist planning counsel: viability assessments, planning risk opinions, and commercial structuring terms.",
      principle: "Always attributed to a named professional, never generated by an LLM.",
    },
    {
      layer: "Layer 4",
      name: "Real-World Ground Truth Evidence",
      icon: ShieldCheck,
      desc: "Physical on-site inspection findings, measured land surveys, intrusive geo-environmental boreholes, and verified highway visibility splays.",
      principle: "The ultimate arbiter of physical reality.",
    },
  ];

  return (
    <>
      <PageHero
        eyebrow="Proprietary Spatial Infrastructure"
        title="Land Radar."
        subtitle="Spatial Intelligence Powering Human Acquisition."
        description="Land Radar is Entire UK's proprietary geospatial screening engine. It continuously reconciles cadastral title boundaries, highways networks, and statutory constraints across the UK to uncover off-market development land with genuine commercial deliverability."
        imageSrc="/images/hero-bg.jpg"
        imageAlt="Cadastral mapping and satellite spatial intelligence overlay"
        badge="Deterministic Infrastructure"
      >
        <div className="flex flex-wrap gap-4 pt-2">
          <Button href="#interactive-demo" variant="primary" showArrow>
            Explore Cadastral Layers
          </Button>
          <Button href="/criteria" variant="secondary">
            View Acquisition Criteria
          </Button>
        </div>
      </PageHero>

      {/* Corporate Position Statement */}
      <section className="bg-brand-carbon border-b border-brand-edge-dark py-6 text-xs font-light text-brand-mist/80">
        <Container>
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-cyan-400 flex-shrink-0" />
              <p>
                <strong className="text-white font-medium">Internal Intelligence Engine:</strong>{" "}
                Land Radar is an internal proprietary decision system used by Entire UK directors to acquire and promote land. We do not sell SaaS software subscriptions or license data to third parties.
              </p>
            </div>
            <Link
              href="/submit"
              className="text-brand-electric hover:underline flex items-center gap-1 whitespace-nowrap"
            >
              <span>Submit Land for Due Diligence</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </Link>
          </div>
        </Container>
      </section>

      {/* The Deterministic Philosophy */}
      <Section dark={true} className="border-b border-brand-edge-dark">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-start">
            <div className="lg:col-span-5 space-y-6">
              <span className="eyebrow eyebrow-dark block">The Core Philosophy</span>
              <h2 className="text-3xl sm:text-4xl font-extralight text-white leading-tight">
                Why We Reject Opaque AI &ldquo;Magic Scores&rdquo;
              </h2>
              <p className="text-base font-light text-brand-mist/85 leading-relaxed">
                Many modern property platforms claim to use artificial intelligence to predict land value. In practice, land is governed by strict statutory legal instruments: title covenants, adopted highways boundaries, drainage easements, and local planning policies.
              </p>
              <p className="text-sm font-light text-brand-mist/75 leading-relaxed">
                A statistical algorithm predicting a 92% viability score cannot detect a 1-metre unadopted ransom strip that renders an entire 20-acre parcel landlocked. Entire UK built Land Radar on an uncompromising deterministic foundation:
              </p>

              <div className="p-4 rounded-sm bg-brand-void border border-white/10 space-y-2">
                <span className="text-[11px] font-mono text-cyan-400 uppercase tracking-wider block">
                  The Epistemic Axiom
                </span>
                <p className="text-sm font-normal text-white italic">
                  &ldquo;Unknown is not clear. Absence of constraint data is not absence of constraint.&rdquo;
                </p>
                <p className="text-xs font-light text-brand-mist/70">
                  Until a constraint is explicitly verified against authoritative statutory geometry, Land Radar flags it as unknown — never as cleared.
                </p>
              </div>
            </div>

            <div className="lg:col-span-7 grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="p-6 rounded-sm bg-brand-void border border-white/10 space-y-3">
                <div className="w-8 h-8 rounded-sm bg-blue-500/10 border border-blue-500/25 flex items-center justify-center text-blue-400">
                  <Scale className="w-4 h-4" />
                </div>
                <h4 className="text-base font-medium text-white">Deterministic Rules</h4>
                <p className="text-xs font-light text-brand-mist/75 leading-relaxed">
                  Every screening result is mathematically explainable. We apply hard spatial rules (e.g. minimum 0.4 ha, contiguous adopted highway frontage, outside Flood Zone 3b) with zero black-box weights.
                </p>
              </div>

              <div className="p-6 rounded-sm bg-brand-void border border-white/10 space-y-3">
                <div className="w-8 h-8 rounded-sm bg-amber-500/10 border border-amber-500/25 flex items-center justify-center text-amber-400">
                  <Layers className="w-4 h-4" />
                </div>
                <h4 className="text-base font-medium text-white">Cadastral Reconciliation</h4>
                <p className="text-xs font-light text-brand-mist/75 leading-relaxed">
                  Physical land parcels rarely match registered Land Registry titles. Land Radar maps the spatial relationship between physical features and legal titles to identify ransom strips and assembly requirements.
                </p>
              </div>

              <div className="p-6 rounded-sm bg-brand-void border border-white/10 space-y-3">
                <div className="w-8 h-8 rounded-sm bg-emerald-500/10 border border-emerald-500/25 flex items-center justify-center text-emerald-400">
                  <Database className="w-4 h-4" />
                </div>
                <h4 className="text-base font-medium text-white">Authoritative Geometry</h4>
                <p className="text-xs font-light text-brand-mist/75 leading-relaxed">
                  Calculations are performed strictly using high-precision British National Grid coordinate transformations (EPSG:27700), eliminating distortions inherent in standard web mapping projections.
                </p>
              </div>

              <div className="p-6 rounded-sm bg-brand-void border border-white/10 space-y-3">
                <div className="w-8 h-8 rounded-sm bg-cyan-500/10 border border-cyan-500/25 flex items-center justify-center text-cyan-400">
                  <UserCheck className="w-4 h-4" />
                </div>
                <h4 className="text-base font-medium text-white">Director Decision Gate</h4>
                <p className="text-xs font-light text-brand-mist/75 leading-relaxed">
                  Algorithms never make acquisition bids. Land Radar prepares an evidence-based investigation file. Progression to negotiation requires written sign-off by an Entire UK Property Director.
                </p>
              </div>
            </div>
          </div>
        </Container>
      </Section>

      {/* Interactive Cadastral Layer Visualizer */}
      <Section id="interactive-demo" dark={true} className="border-b border-brand-edge-dark">
        <Container>
          <div className="max-w-3xl mb-10">
            <span className="eyebrow eyebrow-dark block mb-2">GIS Architecture</span>
            <h2 className="text-3xl sm:text-4xl font-extralight text-white tracking-tight">
              How Land Radar Evaluates a Site
            </h2>
            <p className="text-base font-light text-brand-mist/80 mt-3 leading-relaxed">
              Interact with our multi-layer GIS reconciliation demonstration below to see how physical boundaries, highways networks, and environmental designations converge to establish true development viability.
            </p>
          </div>

          <LandRadarVisualizer />
        </Container>
      </Section>

      {/* Authoritative Data Streams */}
      <Section className="border-b border-brand-edge-light bg-white">
        <Container>
          <div className="max-w-3xl mb-12">
            <span className="eyebrow eyebrow-light block mb-2">Data Ingestion Engine</span>
            <h2 className="text-3xl sm:text-4xl font-extralight text-brand-carbon tracking-tight">
              Ingesting Statutory UK Geospatial Datasets
            </h2>
            <p className="text-base font-light text-brand-slate mt-3 leading-relaxed">
              We aggregate billions of spatial data points from government bodies, statutory agencies, and local authorities, updating records continuously to reflect boundary revisions and policy amendments.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {dataStreams.map((stream, idx) => (
              <div
                key={idx}
                className="bg-white rounded-sm border border-brand-edge-light p-6 sm:p-7 shadow-sm space-y-4 hover:border-brand-steel transition-colors"
              >
                <div className="flex items-center justify-between">
                  <h3 className="text-xl font-light text-brand-carbon">
                    {stream.title}
                  </h3>
                  <span className="text-[10px] font-mono uppercase tracking-widest text-brand-electric bg-brand-surface px-2.5 py-1 rounded-sm border border-brand-edge-light font-medium">
                    {stream.metric}
                  </span>
                </div>
                <p className="text-xs sm:text-sm font-light text-brand-slate leading-relaxed">
                  {stream.desc}
                </p>
                <div className="pt-2 border-t border-brand-edge-light/60 text-xs font-light text-brand-slate/80">
                  <strong className="text-brand-carbon font-medium">Operational Impact:</strong>{" "}
                  {stream.focus}
                </div>
              </div>
            ))}
          </div>
        </Container>
      </Section>

      {/* The 4-Layer Truth Ledger */}
      <Section dark={true} className="border-b border-brand-edge-dark">
        <Container>
          <div className="max-w-3xl mb-12">
            <span className="eyebrow eyebrow-dark block mb-2">Epistemic Rigour</span>
            <h2 className="text-3xl sm:text-4xl font-extralight text-white tracking-tight">
              The 4-Layer Truth Ledger
            </h2>
            <p className="text-base font-light text-brand-mist/80 mt-3 leading-relaxed">
              To prevent subjective optimism from polluting objective spatial facts, Land Radar segregates all candidate intelligence into four immutable layers.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {ledgerLayers.map((l, idx) => {
              const Icon = l.icon;
              return (
                <div
                  key={idx}
                  className="p-6 rounded-sm bg-brand-carbon border border-white/10 flex flex-col justify-between space-y-4"
                >
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-mono uppercase tracking-widest text-cyan-400">
                        {l.layer}
                      </span>
                      <Icon className="w-4 h-4 text-brand-mist/60" />
                    </div>
                    <h3 className="text-lg font-normal text-white">
                      {l.name}
                    </h3>
                    <p className="text-xs font-light text-brand-mist/75 leading-relaxed">
                      {l.desc}
                    </p>
                  </div>

                  <div className="pt-3 border-t border-white/[0.08] text-[11px] font-mono text-cyan-300">
                    &ldquo;{l.principle}&rdquo;
                  </div>
                </div>
              );
            })}
          </div>
        </Container>
      </Section>

      {/* From Signal to Site Visit */}
      <Section surface={true} className="border-b border-brand-edge-light">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
            <div className="lg:col-span-7 space-y-6">
              <span className="eyebrow eyebrow-light block">Human Execution</span>
              <h2 className="text-3xl sm:text-4xl font-extralight text-brand-carbon leading-tight">
                From Digital Signal to Ground Inspection
              </h2>
              <p className="text-base font-light text-brand-slate leading-relaxed">
                Geospatial intelligence only takes an acquisition part of the way. Land value is realised through physical inspection, landowner negotiation, bespoke legal structuring, and expert planning advocacy.
              </p>
              <div className="space-y-3 text-xs sm:text-sm font-light text-brand-slate">
                <div className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                  <p>
                    <strong className="text-brand-carbon font-medium">Physical Walkover:</strong> Every prospective site is walked by an experienced property director to verify access geometry, neighbouring boundary treatments, tree preservation orders, and topography.
                  </p>
                </div>
                <div className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                  <p>
                    <strong className="text-brand-carbon font-medium">Cadastral Counsel Review:</strong> Specialist property solicitors review title deeds, easements, covenants, and drainage outfall rights before committing development capital.
                  </p>
                </div>
                <div className="flex items-start gap-2.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                  <p>
                    <strong className="text-brand-carbon font-medium">Commercial Partnership:</strong> We structure acquisitions transparently with landowners, aligning interests through planning promotion agreements or rapid unconditional completions.
                  </p>
                </div>
              </div>
            </div>

            <div className="lg:col-span-5 bg-brand-surface rounded-sm border border-brand-edge-light p-6 sm:p-8 space-y-5">
              <span className="text-xs font-mono uppercase tracking-wider text-brand-carbon font-semibold block">
                Acquisition Desk Protocol
              </span>
              <div className="space-y-3 text-xs font-light text-brand-slate">
                <p>
                  Landowners, chartered surveyors, and development agents who submit land to Entire UK receive the benefit of our Land Radar spatial analysis free of charge during initial evaluation.
                </p>
                <p>
                  We provide direct, commercial feedback within 5 business days, establishing whether the site warrants a formal acquisition offer or promotion agreement.
                </p>
              </div>

              <div className="pt-2">
                <Button href="/submit/land" variant="primary" showArrow className="w-full justify-center">
                  Submit Land for Spatial Appraisal
                </Button>
              </div>
            </div>
          </div>
        </Container>
      </Section>

      {/* Conversion Banner */}
      <section className="bg-brand-void py-16 sm:py-20 text-white">
        <Container>
          <div className="rounded-sm border border-brand-edge-dark bg-gradient-to-r from-brand-carbon to-brand-void p-8 sm:p-12 flex flex-col md:flex-row items-center justify-between gap-8">
            <div className="max-w-2xl space-y-3">
              <span className="eyebrow eyebrow-dark block">Partner With Us</span>
              <h2 className="text-2xl sm:text-3xl font-extralight text-white">
                Submit an Opportunity for Land Radar Screening
              </h2>
              <p className="text-sm font-light text-brand-mist/80">
                Whether you own edge-of-settlement land, an obsolete commercial asset, or represent a client with strategic parcels, our acquisition desk is ready to review.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-3 w-full md:w-auto flex-shrink-0">
              <Button href="/submit" variant="primary" showArrow>
                Submit an Opportunity
              </Button>
              <Button href="/criteria" variant="secondary">
                Review Acquisition Criteria
              </Button>
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
