-- ============================================================
-- Migration 0004: Sites
-- Entire UK's canonical investigation target entity.
-- A site is NOT automatically an opportunity.
-- ============================================================

CREATE TYPE site_status AS ENUM (
  'candidate',
  'screening',
  'under_review',
  'investigating',
  'due_diligence',
  'controlled',
  'planning',
  'development',
  'completed',
  'declined',
  'archived'
);

CREATE TABLE IF NOT EXISTS sites (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- Internal reference: EUK-S-NNNNN (generated by application layer)
  internal_reference text UNIQUE NOT NULL,
  name text,
  status site_status NOT NULL DEFAULT 'candidate',
  source text NOT NULL DEFAULT 'manual',
  source_reference text,

  -- Geometry: stored EPSG:4326
  -- Area calculated via EPSG:27700 (British National Grid) for metre-accurate results
  -- NEVER use ST_Area on EPSG:4326 for UK land analysis
  geometry geometry(MultiPolygon, 4326),
  centroid geometry(Point, 4326) GENERATED ALWAYS AS (ST_Centroid(geometry)) STORED,
  area_sqm numeric GENERATED ALWAYS AS (
    CASE WHEN geometry IS NOT NULL
    THEN ST_Area(ST_Transform(geometry, 27700))
    ELSE NULL END
  ) STORED,
  -- Source-supplied area retained unmodified for comparison
  area_sqm_source numeric,
  -- Flagged when calculated and source-supplied areas disagree by >5%
  area_discrepancy_flag boolean NOT NULL DEFAULT false,

  -- Location intelligence
  local_authority text,
  country text NOT NULL DEFAULT 'england',
  postcode_sector text,
  location_description text,

  -- Metadata
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Spatial index for geographic queries
CREATE INDEX sites_geometry_idx ON sites USING GIST(geometry);
CREATE INDEX sites_centroid_idx ON sites USING GIST(centroid);
CREATE INDEX sites_reference_idx ON sites (internal_reference);
CREATE INDEX sites_status_idx ON sites (status);
CREATE INDEX sites_la_idx ON sites (local_authority);

CREATE TRIGGER sites_updated_at
  BEFORE UPDATE ON sites
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sites_authenticated" ON sites
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "sites_service_role" ON sites
  FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE sites IS
  'An Entire UK investigation target. A site being identified by Land Radar means: '
  'this site warrants investigation. It does NOT mean planning permission exists, '
  'development is achievable, or acquisition is recommended.';
COMMENT ON COLUMN sites.area_sqm IS
  'Calculated from geometry using ST_Area(ST_Transform(geometry, 27700)). '
  'This is the authoritative area value. Source-supplied values are in area_sqm_source.';
COMMENT ON COLUMN sites.area_discrepancy_flag IS
  'Set to true when area_sqm_source differs from calculated area_sqm by more than 5%. '
  'Both values are retained. Neither is silently overwritten.';
